baseurl = "https://example.com/"
title = "HrOpen"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
titleCutting = true
animateStyle = "animated zoomIn fast"

[[params.navlinks]]
name = "bulletin/"
url = "news/"
